services:
    graphite-statsd:
        image: graphiteapp/graphite-statsd
        restart: always
        ports:
            - "8080:80"
            - "8125:8125/udp"

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes:
            - ./etc/dashboards:/etc/grafana/provisioning/dashboards
            - ./etc/datasources:/etc/grafana/provisioning/datasources
            - ./src:/var/lib/grafana/dashboards
        depends_on:
            - graphite-statsd
