{
 "title": "Proxy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_prefix", "query": "stats.proxy" },
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "dva_host",
    "label": "DVA Host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests to DVA's",
   "type": "timeseries",
   "description": "Time-based display of ALL outgoing requests to DVA's.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "groupByNode(${app_prefix}.${env}.${dva_host}.request.count, 2, 'sumSeries')"
    }
   ]
  },
  {
   "title": "DVA response sizes",
   "type": "barchart",
   "description": "Shows buckets of response sizes based off of DVA responses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "target": "groupByNode(${app_prefix}.${env}.${dva_host}.response.size.*, 5, 'averageSeries')"
    }
   ]
  },
  {
   "title": "Requests Attempts to DVA's",
   "type": "barchart",
   "description": "Time-based display of how many request attempts were made for a single client request.\n\nThe bars in the graph only represent the time when the application stopped making requests. The start time of the requests is not taken into account.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(sortByName(groupByNode(${app_prefix}.${env}.${dva_host}.request.attempt_count.*, 5, 'sumSeries'), true), '$', ' attempts')"
    }
   ]
  },
  {
   "title": "Distribution of Request Attempts to DVA's",
   "type": "piechart",
   "description": "A one-day average distribution of request attempts made for each client request towards DVA's.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasSub(groupByNode(summarize(${app_prefix}.${env}.${dva_host}.request.attempt_count.*, '1d'), 5), '$', ' attempts')"
    }
   ]
  }
 ]
}